/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "LogicBehindCode</>",
  "tagline": "Summarising my Coding Journey",
  "url": "https://ashutoshgautam.dev",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "https://ashutoshgautam.dev/static/media/pf3.90874d7910affe4198b6.png",
  "organizationName": "ashuthe1",
  "projectName": "LogicBehindCode",
  "trailingSlash": false,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/ashuthe1/projects/personal/LogicBehindCode Blogs/sidebars.js",
          "editUrl": "https://github.com/ashuthe1/LogicBehindCode/tree/main/",
          "routeBasePath": "/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": {
          "showReadingTime": true,
          "routeBasePath": "/",
          "editUrl": "https://github.com/ashuthe1/LogicBehindCode/tree/main/"
        },
        "theme": {
          "customCss": "/home/ashuthe1/projects/personal/LogicBehindCode Blogs/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "LogicBehindCode</>",
      "logo": {
        "alt": "LogicBehindCode Logo",
        "src": "https://ashutoshgautam.dev/static/media/pf3.90874d7910affe4198b6.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "algorithms/intro",
          "position": "left",
          "label": "Algorithms"
        },
        {
          "type": "doc",
          "docId": "data-structures/intro",
          "position": "left",
          "label": "Data Structures"
        },
        {
          "type": "doc",
          "docId": "standard-problems/Blind75",
          "position": "left",
          "label": "Standard Problems"
        },
        {
          "type": "doc",
          "docId": "web-development/mongodb",
          "position": "left",
          "label": "Web Development"
        },
        {
          "href": "https://github.com/ashuthe1",
          "label": "GitHub",
          "position": "right"
        },
        {
          "href": "https://www.linkedin.com/in/ashuthe1/",
          "label": "LinkedIn",
          "position": "right"
        },
        {
          "href": "https://ashutoshgautam.dev",
          "label": "Portfolio",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Coding Profiles",
          "items": [
            {
              "label": "LeetCode",
              "href": "https://leetcode.com/ashuthe1/"
            },
            {
              "label": "CodeChef",
              "href": "https://www.codechef.com/users/ashuthe1x"
            },
            {
              "label": "Codeforces",
              "href": "https://codeforces.com/profile/ashutosh_gautam"
            }
          ]
        },
        {
          "title": "Connect",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://leetcode.com/ashuthe1/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/ashuthe1"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/ashuthe1x"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/@LogicBehindCode"
            },
            {
              "label": "PortFolio",
              "href": "https://ashutoshgautam.dev"
            },
            {
              "label": "All my Links!",
              "href": "https://ashuthe1.bio.link/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 - 2024 Ashutosh Gautam, All Right Reserved."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "solidity"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
